In [11]:
import pandas as pd
import numpy as np
from datetime import datetime

<h2>Metrics for each video</h2>

In [12]:
df_agg = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Ken_lee youtube data\Aggregated_Metrics_By_Video.csv").iloc[1:,:]
df_agg.head()

,Video,Video title,Video pub­lish time,Com­ments ad­ded,Shares,Dis­likes,Likes,Sub­scribers lost,Sub­scribers gained,RPM (USD),CPM (USD),Av­er­age per­cent­age viewed (%),Av­er­age view dur­a­tion,Views,Watch time (hours),Sub­scribers,Your es­tim­ated rev­en­ue (USD),Im­pres­sions,Im­pres­sions click-through rate (%)
1,4OZip0cgOho,How I Would Learn Data Science (If I Had to St...,"May 8, 2020",907,9583,942,46903,451,46904,6.353,12.835,36.65,0:03:09,1253559,65850.7042,46453,7959.533,26498799,3.14
2,78LjdAAw0wA,100K Channel Update + AMA Stream!,"Nov 12, 2020",412,4,4,130,15,12,2.668,6.259,6.26,0:05:14,2291,200.2966,-3,6.113,188318,0.72
3,hO_YKK_0Qck,Uber Driver to Machine Learning Engineer in 9 ...,"Jul 16, 2020",402,152,15,881,9,198,9.516,11.695,15.12,0:10:21,21350,3687.3387,189,202.963,442334,2.53
4,uXLnbdHMf8w,Why I'm Starting Data Science Over Again.,"Aug 29, 2020",375,367,22,2622,40,1957,3.143,7.943,33.41,0:02:36,49564,2148.3110,1917,155.779,521185,4.01
5,Xgg7dIKys9E,Interview with the Director of AI Research @ N...,"Aug 5, 2020",329,118,15,590,11,161,2.973,7.425,9.55,0:04:37,13429,1034.3945,150,39.920,210876,3.38

In [4]:
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 1 to 223
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Video                                 223 non-null    object
 1   Video title                           223 non-null    object
 2   Video pub­lish time                   223 non-null    object
 3   Com­ments ad­ded                      223 non-null    int64
 4   Shares                                223 non-null    int64
 5   Dis­likes                             223 non-null    int64
 6   Likes                                 223 non-null    int64
 7   Sub­scribers lost                     223 non-null    int64
 8   Sub­scribers gained                   223 non-null    int64
 9   RPM (USD)                             223 non-null    float64
 10  CPM (USD)                             221 non-null    float64
 11  Av­er­age per­cent­age viewed (%)     223 non-null    float64
 12  Av­er­age view dur­a­tion             223 non-null    object
 13  Views                                 223 non-null    int64
 14  Watch time (hours)                    223 non-null    float64
 15  Sub­scribers                          223 non-null    int64
 16  Your es­tim­ated rev­en­ue (USD)      223 non-null    float64
 17  Im­pres­sions                         223 non-null    int64
 18  Im­pres­sions click-through rate (%)  223 non-null    float64
dtypes: float64(6), int64(9), object(4)
memory usage: 33.2+ KB

In [13]:
df_agg.columns = ['Video','Video_title','Video_publish_time','Comments_added','Shares','Dislikes','Likes',
                      'Subscribers_lost','Subscribers_gained','RPM(USD)','CPM(USD)','Average_%_viewed','Average_view_duration',
                      'Views','Watch_time (hours)','Subscribers','Your_estimated_revenue(USD)','Impressions','Impressions_ctr(%)']

In [14]:
df_agg['Video_publish_time'] = pd.to_datetime(df_agg['Video_publish_time'], format='mixed')#converting to datetime
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 1 to 223
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Video                        223 non-null    object
 1   Video_title                  223 non-null    object
 2   Video_publish_time           223 non-null    datetime64[ns]
 3   Comments_added               223 non-null    int64
 4   Shares                       223 non-null    int64
 5   Dislikes                     223 non-null    int64
 6   Likes                        223 non-null    int64
 7   Subscribers_lost             223 non-null    int64
 8   Subscribers_gained           223 non-null    int64
 9   RPM(USD)                     223 non-null    float64
 10  CPM(USD)                     221 non-null    float64
 11  Average_%_viewed             223 non-null    float64
 12  Average_view_duration        223 non-null    object
 13  Views                        223 non-null    int64
 14  Watch_time (hours)           223 non-null    float64
 15  Subscribers                  223 non-null    int64
 16  Your_estimated_revenue(USD)  223 non-null    float64
 17  Impressions                  223 non-null    int64
 18  Impressions_ctr(%)           223 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(9), object(3)
memory usage: 33.2+ KB

In [15]:
print(df_agg['Video_publish_time'])

1     2020-05-08
2     2020-11-12
3     2020-07-16
4     2020-08-29
5     2020-08-05
         ...
219   2018-11-30
220   2019-05-25
221   2018-12-18
222   2019-05-05
223   2017-06-06
Name: Video_publish_time, Length: 223, dtype: datetime64[ns]

In [16]:
print(df_agg['Average_view_duration'])

1      0:03:09
2      0:05:14
3      0:10:21
4      0:02:36
5      0:04:37
        ...
219    0:03:28
220    0:02:06
221    0:01:52
222    0:03:09
223    0:01:04
Name: Average_view_duration, Length: 223, dtype: object

In [18]:

#df_agg['Average_view_duration'] = df_agg['Average_view_duration'].apply(lambda x: datetime.strptime(str(x), '%H:%M:%S'))
#df_agg['Avg_duration_sec'] = df_agg['Average_view_duration'].apply(lambda x: x.second + x.minute*60 + x.hour*3600)

<h4>viewer Engagement + subs gained </h4>

In [19]:
df_agg['Engagement_ratio'] = (df_agg['Comments_added'] + df_agg['Shares'] + df_agg['Dislikes'] + df_agg['Likes']) /df_agg.Views

In [20]:
df_agg['Views/sub_gained'] =   df_agg['Views'] / df_agg['Subscribers_gained']

In [21]:
df_agg.sort_values('Video_publish_time', ascending=False, inplace=True)

<h4>Loading other datasets</h4>

In [22]:
df_agg_sub = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Ken_lee youtube data\Aggregated_Metrics_By_Country_And_Subscriber_Status.csv")

In [23]:
df_comments = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Ken_lee youtube data\All_Comments_Final.csv")

In [24]:
df_time = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\Ken_lee youtube data\Video_Performance_Over_Time.csv")
df_time['Date'] = pd.to_datetime(df_time['Date'], format='mixed')

<h4>additional data enigneering for aggregated data</h4>

In [42]:
df_agg_diff = df_agg.copy()
df_agg_diff.head()

,Video,Video_title,Video_publish_time,Comments_added,Shares,Dislikes,Likes,Subscribers_lost,Subscribers_gained,RPM(USD),...,Average_%_viewed,Average_view_duration,Views,Watch_time (hours),Subscribers,Your_estimated_revenue(USD),Impressions,Impressions_ctr(%),Engagement_ratio,Views/sub_gained
111,0jTtHYie3CU,Should You Be Excited About Web 3? (As a Data ...,2022-01-17,37,43,8,267,14,18,4.055,...,48.50,0:02:38,4383,192.5779,4,16.549,65130,2.95,0.080995,243.500000
187,2RWwN5ZT4tA,Should @Luke Barousse Take This Data Analyst ...,2022-01-14,12,2,3,78,1,1,1.882,...,70.68,0:00:38,2401,25.9375,0,1.720,25094,2.64,0.039567,2401.000000
64,rEWPqw6rMGI,The Only Data Science Explanation You Need,2022-01-10,62,141,5,722,28,136,5.971,...,35.49,0:04:40,10277,801.5549,108,60.498,215491,2.22,0.090493,75.566176
59,o-wsyxWbPOw,We Need to Talk About The LinkedIn Machine Lea...,2022-01-03,65,36,12,592,10,78,5.321,...,45.08,0:02:46,11808,545.6332,68,62.568,166915,3.32,0.059705,151.384615
32,xpIFS6jZbe8,How I Would Learn Data Science in 2022 (If I H...,2021-12-27,109,767,53,4413,46,2553,6.836,...,36.77,0:04:29,79283,5945.5420,2507,528.286,1420968,3.31,0.067379,31.054837

videos published within the last 12 months

In [27]:
metric_date_12mo = df_agg_diff['Video_publish_time'].max() - pd.DateOffset(months=12)

# Filter rows
filtered_df = df_agg_diff[df_agg_diff['Video_publish_time'] >= metric_date_12mo]

# Select only numeric columns
numeric_cols = filtered_df.select_dtypes(include=[np.number])

# Compute median across rows (axis=0 → column-wise median)
median_agg = np.median(numeric_cols, axis=0)

print(median_agg)

[4.35000000e+01 4.25000000e+01 5.00000000e+00 3.82500000e+02
 1.30000000e+01 5.65000000e+01 4.37000000e+00 1.05730000e+01
 4.11750000e+01 7.41700000e+03 2.79985100e+02 3.85000000e+01
 2.47995000e+01 1.55102500e+05 2.43000000e+00 6.02851587e-02
 1.40146406e+02]

Numeric Columns

In [28]:
numeric_cols = np.array((df_agg_diff.dtypes == 'float64') | df_agg_diff.dtypes == 'int64') #intergers and floats
df_agg_diff.iloc[:, numeric_cols] = (df_agg_diff.iloc[:, numeric_cols])

Merging df_time + df_agg dataframe

In [30]:
# Check column names
print(df_time.columns)
print(df_agg.columns)

Index(['Date', 'Video Title', 'External Video ID', 'Video Length',
       'Thumbnail link', 'Views', 'Video Likes Added', 'Video Dislikes Added',
       'Video Likes Removed', 'User Subscriptions Added',
       'User Subscriptions Removed', 'Average View Percentage',
       'Average Watch Time', 'User Comments Added'],
      dtype='object')
Index(['Video', 'Video_title', 'Video_publish_time', 'Comments_added',
       'Shares', 'Dislikes', 'Likes', 'Subscribers_lost', 'Subscribers_gained',
       'RPM(USD)', 'CPM(USD)', 'Average_%_viewed', 'Average_view_duration',
       'Views', 'Watch_time (hours)', 'Subscribers',
       'Your_estimated_revenue(USD)', 'Impressions', 'Impressions_ctr(%)',
       'Engagement_ratio', 'Views/sub_gained'],
      dtype='object')

In [47]:
# Ensure datetime format
df_time['Date'] = pd.to_datetime(df_time['Date'])
df_agg['Video_publish_time'] = pd.to_datetime(df_agg['Video_publish_time'])

In [54]:
# Merge safely
df_time_diff = pd.merge(df_time, df_agg,left_on = 'External Video ID', right_on='Video', how='left')
df_time_diff['days_published'] = (df_time_diff['Date'] - df_time_diff['Video_publish_time']).dt.days

In [53]:
df_time_diff.head()

,Date,Video Title,External Video ID,Video Length,Thumbnail link,Views_x,Video Likes Added,Video Dislikes Added,Video Likes Removed,User Subscriptions Added,...,Average_view_duration,Views_y,Watch_time (hours),Subscribers,Your_estimated_revenue(USD),Impressions,Impressions_ctr(%),Engagement_ratio,Views/sub_gained,days_published
0,2022-01-19,Kaggle Project From Scratch - Part 2 (Explorat...,KQ80oD_boBM,2191,https://i.ytimg.com/vi/KQ80oD_boBM/hqdefault.jpg,13,0,0,0,0,...,0:06:14,14711.0,1530.1763,125.0,97.815,256448.0,3.01,0.046836,106.601449,376.0
1,2022-01-19,Welcome To My Channel | Ken Jee | Data Science,smeFkHwnM_k,51,https://i.ytimg.com/vi/smeFkHwnM_k/hqdefault.jpg,2,0,0,0,1,...,0:00:28,1225.0,9.6188,47.0,6.115,27960.0,1.01,0.031837,26.063830,1053.0
2,2022-01-19,How She Dominated the FAANG Data Science Inter...,vfV4nm004VQ,2686,https://i.ytimg.com/vi/vfV4nm004VQ/hqdefault.jpg,10,0,0,0,0,...,0:05:43,15766.0,1506.0800,115.0,64.430,224947.0,3.64,0.040340,131.383333,504.0
3,2022-01-19,The 9 Books That Changed My Perspective in 2019,3TrAYmrmA8o,980,https://i.ytimg.com/vi/3TrAYmrmA8o/hqdefault.jpg,1,0,0,0,0,...,0:03:52,3037.0,195.8760,21.0,5.485,60048.0,3.25,0.065196,132.043478,747.0
4,2022-01-19,Interview with the Director of AI Research @ N...,Xgg7dIKys9E,2904,https://i.ytimg.com/vi/Xgg7dIKys9E/hqdefault.jpg,1,0,0,0,0,...,0:04:37,13429.0,1034.3945,150.0,39.920,210876.0,3.38,0.078338,83.409938,532.0

12 months of Data

In [ ]:
date_12mo = df_agg['Video_publish_time'].max() - pd.DateOffset(months=12)
df_time_diff_yr =  df_time_diff[df_time_diff['Video_publish_time'] >= date_12mo]

Create pivot table grouped by days published

In [65]:
print(df_time_diff_yr.columns)

Index(['Date', 'Video Title', 'External Video ID', 'Video Length',
       'Thumbnail link', 'Views_x', 'Video Likes Added',
       'Video Dislikes Added', 'Video Likes Removed',
       'User Subscriptions Added', 'User Subscriptions Removed',
       'Average View Percentage', 'Average Watch Time', 'User Comments Added',
       'Video', 'Video_title', 'Video_publish_time', 'Comments_added',
       'Shares', 'Dislikes', 'Likes', 'Subscribers_lost', 'Subscribers_gained',
       'RPM(USD)', 'CPM(USD)', 'Average_%_viewed', 'Average_view_duration',
       'Views_y', 'Watch_time (hours)', 'Subscribers',
       'Your_estimated_revenue(USD)', 'Impressions', 'Impressions_ctr(%)',
       'Engagement_ratio', 'Views/sub_gained', 'days_published'],
      dtype='object')

In [66]:
views_days = pd.pivot_table(
    df_time_diff_yr,
    index='days_published',
    values='Views_x',
    aggfunc=[np.mean, np.median, lambda x: np.percentile(x, 80), lambda x: np.percentile(x, 20)]
).reset_index()

C:\Users\USER\AppData\Local\Temp\ipykernel_7464\2815034798.py:1: FutureWarning: The provided callable <function mean at 0x0000023C36AE7A60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  views_days = pd.pivot_table(
C:\Users\USER\AppData\Local\Temp\ipykernel_7464\2815034798.py:1: FutureWarning: The provided callable <function median at 0x0000023C36D26FC0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  views_days = pd.pivot_table(

In [67]:
views_days

    days_published         mean  median <lambda>
                        Views_x Views_x  Views_x Views_x
0             -4.0     0.000000     0.0      0.0     0.0
1             -3.0     0.333333     0.0      0.6     0.0
2             -2.0     1.500000     1.0      2.8     0.0
3             -1.0    30.093750     2.0      3.0     1.0
4              0.0  2723.152174  1651.5   4364.0  1106.0
..             ...          ...     ...      ...     ...
358          354.0     7.000000     7.0     10.0     4.0
359          355.0     4.000000     4.0      5.2     2.8
360          358.0     1.000000     1.0      1.0     1.0
361          359.0     2.000000     2.0      2.0     2.0
362          361.0     2.000000     2.0      2.0     2.0

[363 rows x 5 columns]

filter to first 30 days

In [74]:
views_days = views_days[views_days['days_published'].between(0, 30)]

#Create cumulative views DataFrame
views_cumulative = views_days.copy()
views_cumulative[['median_views', 'pct_80', 'pct_20']] = views_cumulative[['median_views', 'pct_80', 'pct_20']].cumsum()

KeyError: "['median_views' 'pct_80' 'pct_20'] not in index"